/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddModelDialog: typeof import('./components/model/AddModelDialog.vue')['default']
    AlbumViewer: typeof import('./components/viewer/AlbumViewer.vue')['default']
    AudioPlayer: typeof import('./components/viewer/AudioPlayer.vue')['default']
    ChatArea: typeof import('./components/search/ChatArea.vue')['default']
    DeleteDialog: typeof import('./components/general/DeleteDialog.vue')['default']
    Dropdown: typeof import('./components/general/Dropdown.vue')['default']
    EditTextField: typeof import('./components/general/EditTextField.vue')['default']
    ExcludedGroups: typeof import('./components/drawers/filters/ExcludedGroups.vue')['default']
    ImageUploadDialog: typeof import('./components/search/ImageUploadDialog.vue')['default']
    Item: typeof import('./components/items/Item.vue')['default']
    ItemOverlay: typeof import('./components/items/ItemOverlay.vue')['default']
    ItemSet: typeof import('./components/drawers/ItemSet.vue')['default']
    LeftPanel: typeof import('./components/model/LeftPanel.vue')['default']
    MediaViewer: typeof import('./components/viewer/MediaViewer.vue')['default']
    Merge: typeof import('./components/drawers/Merge.vue')['default']
    ModelBar: typeof import('./components/model/ModelBar.vue')['default']
    RelatedItemsGrid: typeof import('./components/viewer/RelatedItemsGrid.vue')['default']
    ResultGrid: typeof import('./components/search/ResultGrid.vue')['default']
    RightPanel: typeof import('./components/model/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./components/search/SearchDialog.vue')['default']
    SettingsForm: typeof import('./components/model/SettingsForm.vue')['default']
    TempSearchDialog: typeof import('./components/search/TempSearchDialog.vue')['default']
    VideoPlayer: typeof import('./components/viewer/VideoPlayer.vue')['default']
  }
}
