/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Chat: typeof import('./components/model/Chat.vue')['default']
    CountFilter: typeof import('./components/drawers/filters/CountFilter.vue')['default']
    DeleteDialog: typeof import('./components/general/DeleteDialog.vue')['default']
    Dropdown: typeof import('./components/general/Dropdown.vue')['default']
    EditTextField: typeof import('./components/general/EditTextField.vue')['default']
    ExcludedVideos: typeof import('./components/drawers/filters/ExcludedVideos.vue')['default']
    Filters: typeof import('./components/drawers/filters/Filters.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Item: typeof import('./components/items/Item.vue')['default']
    ItemOverlay: typeof import('./components/items/ItemOverlay.vue')['default']
    ItemSet: typeof import('./components/drawers/ItemSet.vue')['default']
    LeftPanel: typeof import('./components/model/LeftPanel.vue')['default']
    Merge: typeof import('./components/drawers/Merge.vue')['default']
    ModelBar: typeof import('./components/model/ModelBar.vue')['default']
    RangeFilter: typeof import('./components/drawers/filters/RangeFilter.vue')['default']
    RightPanel: typeof import('./components/model/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsForm: typeof import('./components/model/SettingsForm.vue')['default']
    URFGrid: typeof import('./components/model/URFGrid.vue')['default']
  }
}
